### PR TITLE
buildInputToString: Pass along the input's type and urr

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by copumpkin** [comment]
urr!

**Comment by shlevy** [comment]
Hey, I got it right in the code!

**Comment by copumpkin** [comment]
urr, okay :smile:

**Comment by edolstra** [comment]
Hm, shouldn't we set `type` to `derivation` to allow the input to be used as a derivation?

**Comment by shlevy** [comment]
No strong opinions there, if we want to use `inputType` instead I can make that change.

**Comment by edolstra** [comment]
Yeah, having a separate `inputType` attribute is probably better.

**Comment by shlevy** [comment]
OK, updated

**Pull request merged**
