### PR TITLE
Revert to Nix 2.5.1

### PR DESCRIPTION
**Pull request by cole-h**
Hydra has been having mysterious issues recently, and we believe it may be related to the jump from 2.4preXYZ to 2.6.0. We test 2.5.1 as a way to bisect.

### CODE REVIEW

**Comment by cole-h** [comment]
I had to overlay Nix and lowdown because without it, I would see:

```
       > configure: error: Package requirements (lowdown >= 0.8.0) were not met:
       >
       > No package 'lowdown' found
       >
       > Consider adjusting the PKG_CONFIG_PATH environment variable if you
       > installed software in a non-standard prefix.
       >
       > Alternatively, you may set the environment variables LOWDOWN_CFLAGS
       > and LOWDOWN_LIBS to avoid the need to call pkg-config.
       > See the pkg-config man page for more details.
```

**Comment by grahamc** [comment]
Builds and checks pass for me.

**Comment by grahamc** [comment]
```
[nix-shell:~/projects/github.com/NixOS/hydra]$ nix-diff /nix/store/ynnpw0sj4wpw37r83a49cw94qbx12ppz-nix-2.5.1.drv /nix/store/hglrdmqj90d241fhynkvyckn8nb3yh84-nix-2.5.1.drv
- /nix/store/ynnpw0sj4wpw37r83a49cw94qbx12ppz-nix-2.5.1.drv:{out}
+ /nix/store/hglrdmqj90d241fhynkvyckn8nb3yh84-nix-2.5.1.drv:{out}
• The set of input derivation names do not match:
    - 73d5f38a47e7c3dea62994cfb8f962976194f767.patch
• The set of input derivations named `lowdown-0.9.0` do not match
    - /nix/store/v7lzl0fak9wbly6338yf6y7173hrhch3-lowdown-0.9.0.drv:{dev}
• The environments do not match:
    buildInputs=''
    /nix/store/iajslqx0fpnvfvgdxxipx3lr5yg59k1m-curl-7.76.1-dev /nix/store/f8lz7qqwv1pgp6n8f4ibg71nkrsp8s81-bzip2-1.0.6.0.2-dev /nix/store/b7ksvmb7wxcsxvnd5h39cwlk9rrp6s3c-xz-5.2.5-dev /nix/store/lyb99rmgggp7fdfmbpqa9nqmwvv25ldc-brotli-1.0.9-dev /nix/store/dbzwmwalrz67m8dm253nscri86f55xl5-editline-1.17.0-dev /nix/store/7mdjirqjkx4g66bna1c7p4dglzp5j3yr-openssl-1.1.1k-dev /nix/store/fip6b0qr5ky1mipi5ar2ddwyq7x1h8jq-sqlite-3.35.5-dev /nix/store/5kcaqkga5i0bhv2bk1xal6x6nak550hd-libarchive-3.5.1-dev /nix/store/nk7h93lyayx50m483pzyy0gf4rx8vm2g-boost-1.69.0-dev /nix/store/sh8b4h62gqcbrlk57r47i7qf69ia20wc-lowdown-0.9.0-dev /nix/store/2z5p7ixrqsdblmclg0f5sz24vmpgglwk-gtest-1.10.0-dev /nix/store/4hxdqhs68ir0jiing73zjqmzcinj784l-libseccomp-2.5.1-dev /nix/store/0vll9ad3hsmd78z25w0irlsnq0s7rviy-libsodium-1.0.18-dev /nix/store/dn3yd4gxknadlrkd7apsypvg210d8j47-libcpuid-0.5.1 /nix/store/h8gzq2qvml0xwicgb07qh8rg56jci2wq-aws-sdk-cpp-1.8.121-dev /nix/store/g44ld0z3pk45vj7f0r8xiryrrm3qjr4d-lowdown-0.9.0-dev
''
    patches=''
    /nix/store/cawc0s7akimgv115q446m91r74vhf04b-73d5f38a47e7c3dea62994cfb8f962976194f767.patch
''


```

**Comment by cole-h** [comment]
Here's mine I did just now:

```
: 11:27:40 ~/w/de/hydra revert-from-nix-2.6 ; nix-diff /nix/store/hglrdmqj90d241fhynkvyckn8nb3yh84-nix-2.5.1.drv /nix/store/xrb4pnvliq0xq2is4cgxbqb72k301lh6-nix-2.5.1.drv
- /nix/store/hglrdmqj90d241fhynkvyckn8nb3yh84-nix-2.5.1.drv:{out}
+ /nix/store/xrb4pnvliq0xq2is4cgxbqb72k301lh6-nix-2.5.1.drv:{out}
• The input derivation named `lowdown-0.9.0` differs
  - /nix/store/bbfiyw5yjdfvmczmrwz48ra69z74mc04-lowdown-0.9.0.drv:{bin,dev}
  + /nix/store/v7lzl0fak9wbly6338yf6y7173hrhch3-lowdown-0.9.0.drv:{bin,dev}
  • The set of input source names do not match:
      - source
  • The set of input derivation names do not match:
      + source
  • The environments do not match:
      + pname=lowdown
      + version=0.9.0
      configurePhase=''
      
      ./configure \
        PREFIX=/02qcpld1y6xhs5gz9bchpxaw0xdhmsp5dv88lh25r2ss44kh8dxz \
        
                  BINDIR=/04f3da1kmbr67m3gzxikmsl4vjz5zf777sv6m14ahv22r65aac9m/bin
      
  ''
      src=''
      /nix/store/6xc7y7394zh63pk854np4i319b0siswp-source/nix/store/j6p6y5bf6a6qjwwwvzk5rwf4i9576v1q-source
  ''
• Skipping environment comparison
```

image

**Comment by cole-h** [comment]
OK, so I noticed that adding the `nix` input made the `lowdown-src` input be fetched anew, so it was actually using the most recent commit from yesterday... `rm flake.lock && nix flake lock` got us the expected revision of `lowdown-src`, so everything works again....

Weird. (Though maybe not totally unexpected -- I am running `nix (Nix) 2.8.0pre20220311_d532269`.)

**Comment by cole-h** [comment]
@Ma27 @Ericson2314 Just FYI: I reverted your commits that bump us to Nix 2.6 and that depend on Nix 2.6 API stuffs, until we can narrow down the h.n.o issues.

**Comment by Ericson2314** [comment]
@cole-h can you build both of those lowdown derivations and see if only one creates a pkg-config file?

**Comment by Ericson2314** [comment]
I get that this 2.5 bump is hopefully just temporary, but it's still very weird that we need such a thing.

**Comment by cole-h** [comment]
The issue was that it was using the `lowdown` from master -- for whatever reason, updating the lockfile would use the latest version of `lowdown-src` instead of the pinned version. Nuking the lock file and `nix flake lock` again fixed it. Possibly a bug in upstream Nix (and may even be fixed; I'm slightly behind).

Indeed, only the "good" version created the pkg-config file. Maybe something changed upstream in recent versions.

<details><summary>"bad" drv</summary>

```
: 18:04:19 ~ ; nix build /nix/store/bbfiyw5yjdfvmczmrwz48ra69z74mc04-lowdown-0.9.0.drv
: 18:04:21 ~ ; exa -T result-dev/                                                     
result-dev
├── man
│  ├── man1
│  │  ├── lowdown-diff.1
│  │  └── lowdown.1
│  └── man5
│     └── lowdown.5
├── nix-support
│  └── propagated-build-inputs
└── share
   └── lowdown
      └── odt
         └── styles.xml
: 18:04:23 ~ ; exa -T result/                                                         
result
```

</details>

<details><summary>"good" drv</summary>

```
: 18:04:24 ~ ; nix build /nix/store/v7lzl0fak9wbly6338yf6y7173hrhch3-lowdown-0.9.0.drv
: 18:04:48 ~ ; exa -T result-dev/
result-dev
├── include
│  └── lowdown.h
├── lib
│  ├── liblowdown.a
│  └── pkgconfig
│     └── lowdown.pc
├── man
│  ├── man1
│  │  ├── lowdown-diff.1
│  │  └── lowdown.1
│  ├── man3
│  │  ├── lowdown.3
│  │  ├── lowdown_buf.3
│  │  ├── lowdown_buf_diff.3
│  │  ├── lowdown_buf_free.3
│  │  ├── lowdown_buf_new.3
│  │  ├── lowdown_diff.3
│  │  ├── lowdown_doc_free.3
│  │  ├── lowdown_doc_new.3
│  │  ├── lowdown_doc_parse.3
│  │  ├── lowdown_file.3
│  │  ├── lowdown_file_diff.3
│  │  ├── lowdown_gemini_free.3
│  │  ├── lowdown_gemini_new.3
│  │  ├── lowdown_gemini_rndr.3
│  │  ├── lowdown_html_free.3
│  │  ├── lowdown_html_new.3
│  │  ├── lowdown_html_rndr.3
│  │  ├── lowdown_latex_free.3
│  │  ├── lowdown_latex_new.3
│  │  ├── lowdown_latex_rndr.3
│  │  ├── lowdown_metaq_free.3
│  │  ├── lowdown_node_free.3
│  │  ├── lowdown_nroff_free.3
│  │  ├── lowdown_nroff_new.3
│  │  ├── lowdown_nroff_rndr.3
│  │  ├── lowdown_term_free.3
│  │  ├── lowdown_term_new.3
│  │  ├── lowdown_term_rndr.3
│  │  └── lowdown_tree_rndr.3
│  └── man5
│     └── lowdown.5
└── nix-support
   └── propagated-build-inputs
: 18:04:51 ~ ; exa -T result/    
result
```

</details>

**Comment by Ericson2314** [comment]
`2.5-maintainence` gives me `/nix/store/0m285fyyrx6b0d9ydr97skmfxv2yf9ki-lowdown-0.9.0-dev/lib/pkgconfig/lowdown.pc` from the lowdown in the `x86_64-linux` `buildInputs`.

(Ugh. This sort of situation is why I don't like flakes. Due to a mix of inputs and overlays it is extremely confusing how many copies of something one has. When one is just gather up a bunch of executables, this is fine, but when one is trying to use libraries which need to be linked together and have coherent public deps, this is a manifestly bad user experience.)

**Comment by Ericson2314** [comment]
Oh did this not end up having/needing the lowdown thing? Nice!

**Comment by cole-h** [comment]
Nope, it was just some weird issue with locking :)

**Pull request merged**
