### PR TITLE
automatically update github actions

### PR DESCRIPTION
**Pull request by Mic92**
Same as https://github.com/NixOS/nix/pull/3757

### CODE REVIEW

**Comment by edolstra** [comment]
What does this do?

**Comment by Mic92** [comment]
It configures dependabot to automatically create pull requests for github actions like this: Mic92/nixpkgs-review#110

**Comment by Mic92** [comment]
For example install-nix-action v7 no longer works. Having a bot in place automatically take care of this maintenance burden.

**Comment by edolstra** [comment]
Okay, thanks!

**Pull request merged**
