### PR TITLE
`nix-2.21` -> `hydra.nixos.org`

### PR DESCRIPTION
**Pull request by Ericson2314**
Bump to Nix 2.21

~~The tests failed in a local build, I am guessing perhaps due to #1359. @Ma27, would you mind taking a look?~~

### CODE REVIEW

**Comment by Ericson2314** [comment]
Oh nevermind, whatever failure this was just a local thing.

**Comment by Ma27** [comment]
Apologies for not getting back to you btw, was on vacation last week :)

**Comment by Ericson2314** [comment]
@Ma27 all good :)

**Comment by mweinelt** [comment]
Deployed 2.24 based on master to hydra.nixos.org and updated the branch to reflect that.

**Pull request closed without merging**
