### PR TITLE
Fix login if Hydra runs behind HTTP proxy with sub-path location

### PR DESCRIPTION
**Pull request by ck3d**
The used HTTP proxy is nginx.

### CODE REVIEW

**Comment by grahamc** [comment]
Can you explain a little bit about why the old behavior was buggy, and why the new behavior is still correct in the cases where the old one was also correct?

**Comment by ck3d** [comment]
When Hydra location is not at root URL path, a successful login is redirected wrongly to /. We applied this patch to fix this issue.

**Comment by ck3d** [comment]
HTTP referer contains the URL path and oridin does not. Therefor referer is the better default. By the way, the variable is named referer.
see also:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

**Comment by markuskowa** [comment]
Any objection to merging. I am having the same problem. This patch would fix it.

**Pull request merged**
