### PR TITLE
declarative projects: Pull jobset spec build from the remote store

### LINKED ISSUE #443: Declarative projects are broken
Nothing happens after "building" the `.jobsets` jobset.

Calling `hydra-notify` by hand doesn't change anything either.

See https://hydra.mayflower.de/project/mayflower, configuration at:
https://github.com/mayflower/hydra-jobs/blob/master/spec.json
and https://github.com/mayflower/hydra-jobs/blob/master/jobsets.nix

ping @shlevy 

(cc @fpletz, @fadenb)

### PR DESCRIPTION
**Pull request by shlevy**
Fixes #443

### CODE REVIEW

**Comment by shlevy** [comment]
I did test locally that `readNixFile` works as expected for local and remote stores, haven't tested that `handleDeclarativeJobsetBuild` now works for non-local stores but I expect it will.

**Comment by shlevy** [comment]
@globin @domenkozar @edolstra

**Comment by shlevy** [comment]
@k0001 FYI

**Comment by domenkozar** [comment]
Testing this now.

**Comment by domenkozar** [comment]
Using https://github.com/domenkozar/hydra/commits/17.03-stable I can confirm that declarative jobs work now :)

cc @lukego

**Pull request merged**
