### PR TITLE
Fix persistent hash mismatch errors when importing

### LINKED ISSUE #816: Build failures due to 'hash mismatch importing path' in hydra-queue-runner
I'm running into a persistent issue with Hydra and I was hoping someone could help me debug it.

I'm getting the following `hydra-queue-runner` error on one of the build steps:
```
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: possibly transient failure building \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 on \u2018root@tvrasp\u2019: error: --- Error --- hydra-queue-runner                                                                                                                                                           
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: hash mismatch importing path '/nix/store/l39z03xkbqd97iv8737mqpb5ias93dh9-perl5.30.1-XML-LibXML-2.0202-devdoc';
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]:   wanted: sha256:1fjm711i49dyhsdd2ygbr6bznbr289swp7x2xw70mvjjqwqridiz
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]:   got:    sha256:0ms3z0rw17ldmgsq00i9874hs0hzx1qbhwhwmvyhakgmq5bc490c                                          
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: will retry \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 after 544s
```

As far as I understand, this seems to happen while importing the derivation from the remote builder.
The error seems to be persistent, which means that the builds end up getting aborted after some number of retries.
This was happening on only one of the remote builders, when building another derivation (the nix package itself).
However, now the same build step (this perl package) seems to fail with both remote builders, down to the same hash values.

<details><summary>These are all the `hydra-queue-runner` log messages printed when the build step fails.</summary>
<p>

```
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: killing process 36463                                                                                                                    
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: marking build 8113 as failed
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: finishing build step \u2018/nix/store/dsbq2lifkjacf98dnd0sq25adj3fmbg4-linux-config-5.4.65-1.20200914.drv\u2019
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: dispatcher woken up
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: dispatcher sleeping for 40s
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: performing step \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 1 times on \u2018root@tvrasp\u2019 (needed by build 8109 and 0 others)                                                                             
Sep 16 16:11:20 homeserv hydra-queue-runner[108594]: sending closure of \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 to \u2018root@tvrasp\u2019
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: building \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 on \u2018root@tvrasp\u2019
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: outputs of \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 substituted or already valid on \u2018root@tvrasp\u2019
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: copying outputs of \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 from \u2018root@tvrasp\u2019 (1006192 bytes)
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: acquiring write lock on '/nix/var/nix/temproots/108610'                                                                                  
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: downgrading to read lock on '/nix/var/nix/temproots/108610'                                                                           
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: acquiring write lock on '/nix/var/nix/temproots/108610'
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: downgrading to read lock on '/nix/var/nix/temproots/108610'
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: locking path '/nix/store/l39z03xkbqd97iv8737mqpb5ias93dh9-perl5.30.1-XML-LibXML-2.0202-devdoc'
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: lock acquired on '/nix/store/l39z03xkbqd97iv8737mqpb5ias93dh9-perl5.30.1-XML-LibXML-2.0202-devdoc.lock'
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: lock released on '/nix/store/l39z03xkbqd97iv8737mqpb5ias93dh9-perl5.30.1-XML-LibXML-2.0202-devdoc.lock'
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: killing process 45914                                                                                                                    
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: will disable machine \u2018root@tvrasp\u2019 for 65s                                                                                               
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: possibly transient failure building \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 on \u2018root@tvrasp\u2019: error: --- Error --- hydra-queue-runner                                                                                                                                                           
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: hash mismatch importing path '/nix/store/l39z03xkbqd97iv8737mqpb5ias93dh9-perl5.30.1-XML-LibXML-2.0202-devdoc';
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]:   wanted: sha256:1fjm711i49dyhsdd2ygbr6bznbr289swp7x2xw70mvjjqwqridiz
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]:   got:    sha256:0ms3z0rw17ldmgsq00i9874hs0hzx1qbhwhwmvyhakgmq5bc490c                                          
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: will retry \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 after 544s
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: step \u2018/nix/store/9z25c4bngm1a3s72sgd9dnqcrz9197zq-perl5.30.1-XML-LibXML-2.0202.drv\u2019 is now runnable
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: dispatcher woken up                                                                                                                      
Sep 16 16:11:21 homeserv hydra-queue-runner[108594]: dispatcher sleeping for 40s                                                                                                       
```

</p>
</details>

This is my `/etc/nix/machines` file in my Hydra server, for reference:
```
root@tvrasp aarch64-linux /etc/nix/tvrasp 1 20 big-parallel 
localhost builtin,i686-linux,x86_64-linux - 32 1 big-parallel,kvm,nixos-test 
root@builda64 aarch64-linux /etc/nix/builda64 4 1 big-parallel 
```

Any ideas on how I can debug this problem?

### PR DESCRIPTION
**Pull request by wizeman**
This would start happening if the network connection between the Hydra
server and the remote build server breaks after sucessfully importing
at least one output of a derivation, but before having finished
importing all outputs.

Fixes #816.

### CODE REVIEW

**Comment by wizeman** [comment]
cc @edolstra

**Comment by ajs124** [comment]
@grahamc As discussed in IRC, we've been running this since the end of November, but I don't remember if we were observing this or why I added it, although I guess I had a reason (thanks past me for writing a useless commit message).

**Comment by grahamc** [comment]
```
19:58 <gchristensen> ajs124: coming back to that PR a few minutes later I think I get it
19:59 <gchristensen> addToStore won't read from source2 if it has the path already, meaning it'd say "Send me path X" remote would say "Here's path X"... but the receiver wouldn't read it, then on the next output it'd say "please send me path Y" and now it is reading path X's data
```

https://github.com/NixOS/nix/blob/c189031e8be0530d73a817571ad7f81ad5eedce6/src/libstore/local-store.cc#L1117 confirms this.

**Comment by grahamc** [comment]
:+1: confirmed this fixes the issue, thank you! Note: I tried to write an automatic test for this using multiple stores, but no luck :/

**Pull request merged**
