### PR TITLE
Update to Nix 2.11.0 and Nixpkgs 22.05

### PR DESCRIPTION
**Pull request by edolstra**
There was some breakage due to the new auto-chroot feature in Nix 2.10, which doesn't handle correctly the case where `$NIX_STORE_DIR` etc. are set.

### CODE REVIEW

**Comment by Ericson2314** [comment]
BTW what commit/PR is this new feature on the Nix side? Just want to stay up to date with these things for doc purposes etc.

**Comment by cole-h** [comment]
I believe that would be https://github.com/NixOS/nix/pull/6714.

**Comment by Ericson2314** [comment]
Thanks!

**Review by NickCao — COMMENTED** [review]
Does this fix https://github.com/NixOS/nix/issues/6981

**Pull request merged**
