### PR TITLE
Remove the Jobs table

### PR DESCRIPTION
**Pull request by edolstra**
The `Jobs` has been superfluous for a long time.

This PR also bumps PostgreSQL to 11 (since that's what hydra.nixos.org uses).

### CODE REVIEW

**Comment by grahamc** [comment]
I'd like to get someone to take a look at this before merging, pinging them separately.

**Comment by grahamc** [comment]
Got a :+1: that this isn't going to cause headache.

**Comment by grahamc** [comment]
_of course, just to clarify, we'd go ahead with this either way -- just wanted to give a heads up_

**Comment by cole-h** [comment]
Just as a historical note: the Jobs relationship was missed and wasn't removed from the Jobsets schema; this is fixed in https://github.com/NixOS/hydra/pull/964.

**Pull request merged**
