### PR TITLE
Fix api/push-github

### LINKED ISSUE #309: /api/push-github broken
Github reports a 500 response from http://hydra.nixos.org/api/push-github for the NixOS/nix repo.

### PR DESCRIPTION
**Pull request by expipiplus1**
Fixes #309

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by domenkozar** [comment]
@expipiplus1 you're using push-github successfully right?

**Comment by expipiplus1** [comment]
@domenkozar yes, it's working very well.

**Comment by domenkozar** [comment]
I've confirmed this fix works.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
