### PR TITLE
fix nar endpoint for binary cache hosting

### PR DESCRIPTION
**Pull request by cleverca22**

### CODE REVIEW

**Comment by Mindavi** [comment]
So, I'm now seeing the following log line pop up in my hydra logs:

```
Oct 13 19:46:33 nixos-asus hydra-evaluator[3276289]: Couldn't require Hydra::Plugin::S3Backup : Global symbol "$MACHINE_LOCAL_STORE" requires explicit package name (did you forget to declare "my $MACHINE_LOCAL_STORE"?) at /nix/store/2r0v1zjwfbl25p6rl109rv7ai5ssmh5x-hydra-0-unstable-2024-09-24-mindavi/libexec/hydra/lib/Hydra/Plugin/S3Backup.pm line 95.
Oct 13 19:46:33 nixos-asus hydra-evaluator[3276289]: Compilation failed in require at /nix/store/zklv83xga1w14g6zll3910zabks0az7d-hydra-perl-deps/lib/perl5/site_perl/5.38.2/Module/Runtime.pm line 314.
Oct 13 19:46:33 nixos-asus hydra-evaluator[3276289]:  at /nix/store/zklv83xga1w14g6zll3910zabks0az7d-hydra-perl-deps/lib/perl5/site_perl/5.38.2/Module/Pluggable.pm line 32.
```

I feel something's not completely going as it's supposed to go.

**Comment by Mic92** [comment]
Does adding `use Nix::Store;` fixes it?

**Comment by Mindavi** [comment]
No, does not seem to help anything.

**Comment by Mindavi** [comment]
@Mic92 I found what to do and made a PR that fixes it. Applied [this](https://github.com/Mindavi/nixos-configuration/commit/dbadf6d4eca050fc11b72e1108fe97acddaabb66) locally and that seems to work, made a PR with that fix too.

**Pull request merged**
