### PR TITLE
product list: convert to a proper table

### LINKED ISSUE #288: Display build products in table format
If a build produces several products, the current design looks kind of messy. See my attached screenshot below. I propose formatting the build products like a table instead, just as "Changes" and "Previous builds". That would also allow for more info (like product size) to be displayed directly without clicking "Details".

Possibly, the build products could even have a dedicated tab (like "Inputs", "Build steps" etc).

**Current look:**

build_products

### PR DESCRIPTION
**Pull request by domenkozar**
This is a slight UI change to improve readability of the product list table.

Fixes #288

2016-05-12-200405_1301x420_scrot

cc @edolstra @rickynils

### CODE REVIEW

**Comment by domenkozar** [comment]
@rickynils does this look better than currently?

**Comment by rickynils** [comment]
@domenkozar Yes, much better! Haven't tested it locally, but it certainly looks merge-worthy.

**Comment by domenkozar** [comment]
Example: https://hydra.snabb.co/build/3403

**Comment by copumpkin** [comment]
Looks good to me. Minor nitpick: I wouldn't put the "Icon" heading in the table. It's pretty obvious that it's an icon (except that many times it isn't!) and it just seems weird. I don't think there's anything wrong with having an empty table heading, FWIW.

**Comment by domenkozar** [comment]
@copumpkin fixed

**Comment by domenkozar** [comment]
@edolstra thoughts?

**Comment by domenkozar** [comment]
As original build has been recycled, here's another example in the wild: https://hydra.snabb.co/build/378266

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
