### PR TITLE
Introduced parallel bzip2

### PR DESCRIPTION
**Pull request by aycanirican**

### CODE REVIEW

**Comment by aycanirican** [comment]
@domenkozar I guess it's a cleaner PR.

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by domenkozar** [comment]
@aycanirican maybe the default could be `0` which means `nproc --all`?

**Comment by aycanirican** [comment]
@domenkozar -p doesn't support zero value (http://bazaar.launchpad.net/~pbzip2/pbzip2/trunk/view/head:/pbzip2.cpp#L3501) but we may want to remove "-p" parameter for autodetecting number of cpus.

**Comment by domenkozar** [comment]
Sounds good, if `0` is set, remove the `-p`

**Comment by aycanirican** [comment]
Ups, screwed again.

**Comment by aycanirican** [comment]
I'll try to open a new pr for this again.

**Pull request closed without merging**
