### PR TITLE
Add GitlabPulls input plugin

### PR DESCRIPTION
**Pull request by nlewo**

### CODE REVIEW

**Comment by nlewo** [comment]
cc @shlevy

**Comment by Shados** [comment]
@nlewo in light of #512, I would suggest changing the plugin slightly to something like [this](https://gist.github.com/Shados/34939268a6d30589d017b16a93abb088).

This also includes support for using a personal access token (PAT) in order to access protected or private repositories. Using the *target* repository URL along with the merge-request ref instead of the source repository url and branch is necessary to avoid running into issues if the source repository is not actually accessible to the user Hydra is authenticating as.

I'm running this modified version of the plugin internally at work, and haven't had any issues thus far.

**Comment by nlewo** [comment]
@Shados Thanks for your patch. I applied it and it works well.
@edolstra Could you please take a look?

**Comment by Ericson2314** [comment]
I have used this and can confirm is does the thing. Please merge!

**Comment by Ericson2314** [comment]
Thanks @shlevy!

**Pull request merged**
