### PR TITLE
Add basic documentation for declarative projects

### PR DESCRIPTION
**Pull request by shlevy**
cc @vcunat for docbookification offer.

### CODE REVIEW

**Comment by domenkozar** [comment]
Once Hydra builds again I'll happily test this - thanks

**Comment by shlevy** [comment]
@vcunat Are you still willing to translate docs to docbook?

**Comment by vcunat** [comment]
Done now: https://github.com/NixOS/hydra/pull/418

I'm sorry I somehow left this behind and completely forgot.

**Comment by shlevy** [comment]
Closed in favor of #418

**Comment by vcunat** [comment]
Not closed, apparently.

**Pull request closed without merging**
